- README.md
- src_new/controllers/gpt.js
pass parameter pwtsz in openwrap for winning bid. UOE-3621
> Pass pwtsz in openwrap

- init-build.sh
- package.json
- src_new/config.js
Pull pwtsz changes into individual-logs branch
> Build optimization

- init-build.sh
Staged nightly for 2.16 Prebid Upgrade Changes
> Staged nightly for 2.16 Prebid Upgrade Changes

- src_new/controllers/gpt.js
- test/controllers/gpt.spec.js
GPT flow was not resuming as soon as all bidders have responded.
we have added a new flag in bid-manager per slot that will be set on receiving bids from all bidders, we will read the value of this flag using setInterval and take action accordingly.
> Gpt timeout issue

- src_new/adapters/prebid.js
Execute DFP call as soon as all bids are recieved
> GPT Timeout Fix

- src_new/util.js
Fix for CriteoID
Fir for PubCommonId
Sending Eids to PubMaticServer
Fix for extra log in case of regex.
> IdentityHub

- src_new/controllers/custom.js
- test/controllers/custom.spec.js
Checker whether bid is available from each bidder or time has exceeded the global timeout fix.
We have changed the condition to check with time instead of maintaining an internal timer variable.
> Timer fix for Custom JS

- init-build.sh
- src_new/adapters/prebid.js
- src_new/bidManager.js
- src_new/conf.js
- src_new/controllers/custom.js
- src_new/controllers/gpt.js
- src_new/controllers/uas.js
- src_new/util.js
- test/bidManager.spec.js
- test/util.spec.js
Contains
#GDPR fix
#Log Device Platform
#prebid upgrade to 3.14
> OpenWrap Nightly Release 19.2.0

- src_new/adapters/prebid.js
- src_new/config.js
- src_new/constants.js
- test/config.spec.js
> Schain Related Changes

- src_new/constants.js
- src_new/controllers/gpt.js
- src_new/util.js
- test/util.spec.js
* Added Hooks on RequestBids which should be supported with prebid > 3.3
* Added userIdAsEids support in getIds()
> IdHub Features

- src_new/controllers/custom.js
- src_new/controllers/gpt.js
- test/controllers/gpt.spec.js
Do not send pubmatic buyerId if pubmatic is not winning.
> Buyer idfix

- src_new/conf.js
- src_new/config.js
- src_new/constants.js
- src_new/controllers/gpt.js
Publisher can change namespace they are using for Prebid from UI.
> Custom NameSpace for Prebid in IH

- src_new/adapters/prebid.js
- src_new/controllers/gpt.js
> Support for Britepool Id params

- src_new/util.js
- test/util.spec.js
> Revert "fix for mapping check"

- src_new/adapters/prebid.js
- src_new/util.js
- test/util.spec.js
> Revert "Feature/outstream"

- src_new/adapters/prebid.js
regex support for PBJS analytics
> UOE 5661: regex support for PBJS analytics

- src_new/adapters/prebid.js
- src_new/bid.js
- src_new/util.js
Log 0x0 in KGPV for video format in logger and tracker.
> Video size 

- src_new/adapters/prebid.js
- src_new/bid.js
- src_new/controllers/custom.js
- src_new/util.js
- test/util.spec.js
Pulling video size changes in prebid same branch since we need the sz change validation in both branchges
> Staged nightly

- init-build.sh
- src_new/adapters/prebid.js
- src_new/bidManager.js
- src_new/controllers/gpt.js
OpenWrap v21.0.0 Stable Release
Based on Prebid 3.25
> OpenWrap v21.0.0

- gulpfile.js
- src_new/controllers/custom.js
- src_new/controllers/gpt.js
- src_new/util.js
[5231] Firing native wrapper tracker for corresponding BID
> [5231] Native Creative rendering in friendly iframe using OW creative template while using prebid analytics

- gulpfile.js
- init-build.sh
- src_new/constants.js
> Prebid Upgrade to 4_25

- gulpfile.js
- init-build.sh
- src_new/constants.js
* my commit message
* Updated the constant and gulp file to add ADOMAIN
Co-authored-by: pramod pisal <pramod.pisal@pubmatic.com>
Co-authored-by: Shashank <Shashank@Shashank.local>
> Prebid Upgrade to 4_25 (#239)

- src_new/adapters/prebid.js
[UOE-6188] Added id field along with siteId for ix (IndexExchange)
> Added id field along with siteId for ix

- src_new/owt.js
Removed the comment which was removing the code for SFDisplayCreative
> Removed the comment which was removing the code for SFDisplayCreative

- build.sh
- gulpfile.js
- src_new/bidManager.js
- src_new/controllers/custom.js
- src_new/controllers/gpt.js
- src_new/util.js
- test/bidManager.spec.js
Added support for Native in Prebid same functionality
> merged with 433 changes for native

- src_new/adapters/prebid.js
- src_new/controllers/idhub.js
Fixes #264 
The only case where this fails if ccpa and gdpr is enabled and both consent are being provided by CMP, we won't set the correct config for GDPR .
This PR will fix it and will be available in OpenWrap nightly releasing on 1st June 2021
> Fix for Consent Management

- src_new/adapters/prebid.js
- src_new/bidManager.js
- src_new/constants.js
- src_new/controllers/custom.js
- src_new/controllers/gpt.js
- src_new/owt.js
- src_new/util.js
- test/bidManager.spec.js
- test/controllers/gpt.spec.js
Added au and mt parameters in Logger and Tracker. For logging AdUnit is and requested ad formats.
> Added au and mt parameters in Logger and Tracker

- src_new/adapters/prebid.js
- src_new/constants.js
- src_new/owt.js
Added javaScript API for setting timeout
> Added javaScript API for setting timeout

- src_new/config.js
- test/config.spec.js
* Ab Test Timeout
* Fix Unit Test case and path to config file
* Code Review Comments
* Fix for bug on timeout
* Initial Approach for AB Test Partners
* AB Test partner unit test cases
* Review comments
* Code Review Comments
* Updated the constant value
* unit test case if control partner is undefined
* Changed condition for checking the key in toObejct
* Fix codacy issue
* changes for identity partner if test is enabled and control/test is not defined
* code review changes
* Code Review comments
* changes for specific test case of no identity partner in control/test
Co-authored-by: pm-shashank-jain <shashank.jain@pubmatic.com>
Co-authored-by: Azhar <azhar@L1119.local>
Co-authored-by: Shashank <Shashank@Shashank.local>
> Feature/abtest (#292)

- src_new/adapters/prebid.js
- src_new/config.js
- src_new/constants.js
- test/adapters/prebid.spec.js
- test/config.spec.js
Added support for floors module. 
For now, config from conf.js will be passed to prebid.
> Added support for floors module

- src_new/util.js
- test/util.spec.js
Auction Macro replacement for Deepintent
> Auction Macro replacement for Deepintent

- src_new/owt.js
Exposed a function for OpenWrap alias which can be used in Prebid fork for accessing biider aliases.
> Exposed a function for OpenWrap bidder alias

- src_new/adapters/prebid.js
- src_new/bid.js
- src_new/bidManager.js
- src_new/config.js
- src_new/constants.js
- src_new/controllers/gpt.js
- test/adapters/prebid.spec.js
Added support for Hybrid in openwrap using PBS
> Hybrid support in openwrap

- src_new/adapters/prebid.js
- test/controllers/custom.spec.js
- test/controllers/gpt.spec.js
Aligned pubmatic adapter entry at top
> UOE-8113: Aligned pubmatic adapter entry at top

- init-build.sh
- src_new/constants.js
- src_new/controllers/idhub.js
- src_new/util.idhub.js
- src_new/util.js
- test/util.spec.js
> Prebid Upgrade to 6.29.3

- src_new/adapters/prebid.js
- src_new/util.js
Marked ignoreBidderCacheKey as true
> Marked ignoreBidderCacheKey as true
